const reviewWords = [
  'good',
  'bad',
  'great',
  'excellent',
  'amazing',
  'incredible',
  'terrible',
  'awful',
  'the worst',
  'boring',
  'interesting',
  'uninteresting',
  'unique',
  'disturbing',
  'enlightening',
  'clever',
  'beautiful',
  'masterpiece',
  `A haunting symphony of words that lingers in the soul.`,
  `Each line is a brushstroke, painting emotions I didn't know I had.`,
  `This poem is a journey through the human heart—simply breathtaking.`,
  `Beautifully crafted, with a rhythm that dances off the page.`,
  `A masterpiece of minimalism, every word perfectly placed.`,
  `This poem touched my spirit and stayed with me long after reading.`,
  `Short yet powerful, this poem packs an emotional punch.`,
  `Pure, unadulterated brilliance in verse form.`,
  `A delicate balance of simplicity and depth—this poem is unforgettable.`,
  `An emotional rollercoaster condensed into a few beautiful lines.`,
  `This poem is a beacon of light in the darkness of everyday life.`,
  `An elegant portrayal of love, loss, and everything in between.`,
  `A soulful expression that left me both reflective and inspired.`,
  `An evocative blend of imagery and emotion—truly moving.`,
  `A poetic gem that captures the essence of longing and hope.`,
  `The words flow like a river, carrying the reader on a journey of discovery.`,
  `It feels like the poet reached into my heart and put my feelings into words.`,
  `A poetic marvel that resonates with universal truths.`,
  `Captivating from the first word to the last.`,
  `The poet's voice shines through every stanza—a true work of art.`,
];

export const mockReviews = new Array(10).fill(0).map(() => ({
  title: 'test-title',
  author: 'test-author',
  rating: Math.floor(1 + Math.random() * 5), // [1, 5]
  review: reviewWords[Math.floor(Math.random() * reviewWords.length)],
}));
